apiVersion: sitewhere.io/v1alpha3
kind: SiteWhereMicroservice
metadata:
  name: event-sources
{{include "sitewhere.microservice.metadata" . | indent 2 }}
  labels:
{{include "sitewhere.microservice.labels" . | indent 4 }}
spec:
{{include "sitewhere.microservice.spec" . | indent 2 }}
  name: Event Sources
  description: Handles inbound device data from various sources, protocols, and formats
  icon: forward
  functionalArea: event-sources
  configuration: {}
{{include "sitewhere.helm.environment" . | indent 2 }}
  podSpec:
{{include "sitewhere.docker.environment" . | indent 4 }}
    ports:
      - containerPort: 9000
      - containerPort: 9090
    env:
{{include "sitewhere.microservice.environment" . | indent 6 }}
      - name: "sitewhere.config.k8s.name"
        value: "event-sources"
  serviceSpec:
{{include "sitewhere.microservice.service" . | indent 4 }}
    ports:
      - port: 9000
        targetPort: 9000
        protocol: TCP
        name: grpc-api
      - port: 9090
        targetPort: 9090
        protocol: TCP
        name: http-metrics
  debug:
    enabled: false
    jdwpPort: 8008
    jmxPort: 1108
{{include "sitewhere.microservice.logging" . | indent 2 }}
      - logger: com.sitewhere.sources
        level: info
    