apiVersion: sitewhere.io/v1alpha3
kind: SiteWhereMicroservice
metadata:
  name: schedule-management
{{include "sitewhere.microservice.metadata" . | indent 2 }}
  labels:
{{include "sitewhere.microservice.labels" . | indent 4 }}
spec:
{{include "sitewhere.microservice.spec" . | indent 2 }}
  name: Schedule Management
  description: Supports scheduling of various system operations
  icon: label
  functionalArea: schedule-management
  configuration: {}
{{include "sitewhere.helm.environment" . | indent 2 }}
  podSpec:
{{include "sitewhere.docker.environment" . | indent 4 }}
    ports:
      - containerPort: 9000
      - containerPort: 9090
    env:
{{include "sitewhere.microservice.environment" . | indent 6 }}
      - name: "sitewhere.config.k8s.name"
        value: "schedule-management"
  serviceSpec:
{{include "sitewhere.microservice.service" . | indent 4 }}
    ports:
      - port: 9000
        targetPort: 9000
        protocol: TCP
        name: grpc-api
      - port: 9090
        targetPort: 9090
        protocol: TCP
        name: http-metrics
  debug:
    enabled: false
    jdwpPort: 8018
    jmxPort: 1118 
{{include "sitewhere.microservice.logging" . | indent 2 }}
      - logger: com.sitewhere.schedule
        level: info
    