apiVersion: sitewhere.io/v1alpha3
kind: SiteWhereMicroservice
metadata:
  name: inbound-processing
{{include "sitewhere.microservice.metadata" . | indent 2 }}
  labels:
{{include "sitewhere.microservice.labels" . | indent 4 }}
spec:
{{include "sitewhere.microservice.spec" . | indent 2 }}
  name: Inbound Processing
  description: Common processing logic applied to enrich and direct inbound events
  icon: input
  functionalArea: inbound-processing
  configuration: {}
{{include "sitewhere.helm.environment" . | indent 2 }}
  podSpec:
{{include "sitewhere.docker.environment" . | indent 4 }}
    ports:
      - containerPort: 9000
      - containerPort: 9090
    env:
{{include "sitewhere.microservice.environment" . | indent 6 }}
      - name: "sitewhere.config.k8s.name"
        value: "inbound-processing"
  serviceSpec:
{{include "sitewhere.microservice.service" . | indent 4 }}
    ports:
      - port: 9000
        targetPort: 9000
        protocol: TCP
        name: grpc-api
      - port: 9090
        targetPort: 9090
        protocol: TCP
        name: http-metrics
  debug:
    enabled: false
    jdwpPort: 8007
    jmxPort: 1107
{{include "sitewhere.microservice.logging" . | indent 2 }}
      - logger: com.sitewhere.inbound
        level: info
    